CATEGORIES = ['Beef', 'Chicken', 'Dessert', 'Lamb', 'Miscellaneous', 'Pasta', 'Pork', 'Seafood', 'Side', 'Starter',
              'Vegan', 'Vegetarian', 'Breakfast', 'Goat']

AREAS = ['Algerian', 'American', 'Argentinian', 'Australian', 'British', 'Canadian', 'Chinese', 'Croatian', 'Dutch',
         'Egyptian', 'Filipino', 'French', 'Greek', 'Indian', 'Irish', 'Italian', 'Jamaican', 'Japanese', 'Kenyan',
         'Malaysian', 'Mexican', 'Moroccan', 'Norwegian', 'Polish', 'Portuguese', 'Russian', 'Saudi Arabian',
         'Slovakian', 'Spanish', 'Syrian', 'Thai', 'Tunisian', 'Turkish', 'Ukrainian', 'Uruguayan', 'Venezulan',
         'Vietnamese']

INGREDIENTS = ['Ackee', 'All purpose flour', 'All-purpose Seasoning', 'Allspice', 'Allspice Berries', 'Almond Essence',
               'Almond Extract', 'Almond Flour', 'Almond Milk', 'Almond Paste', 'Almonds', 'Ancho Chillies',
               'Anchovy Fillet', 'Apple Cider Vinegar', 'Apples', 'Appleton rum', 'Apricot', 'Apricot Jam',
               'Arabic Rice', 'Asparagus', 'Aubergine', 'Avacado Hass Pulp', 'Avocado', 'Baby Aubergine',
               'Baby Lettuce Leaves', 'Baby New Potatoes', 'Baby Pak Koi', 'Baby Plum Tomatoes', 'Baby Squid', 'Bacon',
               'Bacon lardon', 'Baguette', 'Baked Beans', 'Baking Powder', 'Balsamic Vinegar', 'Bamboo Shoot', 'Banana',
               'Barbeque Sauce', 'Basil', 'Basil Leaves', 'Basmati Rice', 'Bay Leaf', 'Bay Leaves', 'Bean Sprouts',
               'Beef', 'Beef Brisket', 'Beef Cutlet', 'Beef Fillet', 'Beef Flank Steak', 'Beef Gravy', 'Beef Kidney',
               'Beef Shin', 'Beef Stock', 'Beef Stock Concentrate', 'Beef Stock Cubes', 'Beef tomatoes', 'Beer',
               'Beetroot', 'Bicarbonate Of Soda', 'Birds-eye Chillies', 'Biryani Masala', 'Black Beans',
               'Black Cardamom Pods', 'Black Olives', 'Black Pepper', 'Black Pudding', 'Black Treacle', 'Blackberries',
               'Blackcurrant Jam', 'Blue Food Colouring', 'Blueberries', 'Boiling Water', 'Bok Choi', 'Borlotti Beans',
               'Bouillon Cubes', 'Bouquet Garni', 'Bowtie Pasta', 'Braeburn Apples', 'Bramley Apples', 'Brandy',
               'Bread', 'Bread Flour', 'Bread Rolls', 'Breadcrumbs', 'Brie', 'Broad Beans', 'Broccoli', 'Brown Lentils',
               'Brown Rice', 'Brown Rice Noodle', 'Brown Sugar', 'Brussels Sprouts', 'Bryndza cheese', 'Buckwheat',
               'Buckwheat Flour', 'Bulgur Wheat', 'Bun', 'Buns', 'Butter', 'Butter Beans', 'Buttermilk',
               'Butternut Squash', 'Cabbage', 'Cabbage Leaves', 'Cacao', 'Cajun', 'Callaloo', 'Can of chickpeas',
               'Candied Peel', 'Canned Tomatoes', 'Cannellini Beans', 'Canola Oil', 'Capers', 'Caramel',
               'Caramel Sauce', 'Caramelized Sugar Sauce', 'Caraway Seed', 'Cardamom', 'Carrots', 'Casabe',
               'Cashew Nuts', 'Cashews', 'Cassaba', 'Caster Sugar', 'Cayenne Pepper', 'Celeriac', 'Celery',
               'Celery Salt', 'Challots', 'Charlotte Potatoes', 'Cheddar Cheese', 'Cheese', 'Cheese Curds',
               'Cheese Slices', 'Cherry', 'Cherry Tomatoes', 'Chestnut Mushroom', 'Chestnuts', 'Chicken',
               'Chicken Bouillon Powder', 'Chicken Breast', 'Chicken Breasts', 'Chicken Legs', 'Chicken Liver',
               'Chicken Stock', 'Chicken Stock Concentrate', 'Chicken Stock Cube', 'Chicken Thighs', 'Chicken Wings',
               'Chicken drumsticks', 'Chickpea Flour', 'Chickpeas', 'Chili Powder', 'Chilled Butter', 'Chilli',
               'Chilli Bean Paste', 'Chilli Flakes', 'Chilli Powder', 'Chilli Sauce', 'Chimichurri sauce',
               'Chinese Broccoli', 'Chinese Cabbage', 'Chinese Leaf', 'Chinese Long Beans', 'Chinese Sesame Sauce',
               'Chinese five spice powder', 'Chives', 'Chocolate Chips', 'Chopped Chive', 'Chopped Onion',
               'Chopped Parsley', 'Chopped Tomatoes', 'Chorizo', 'Christmas Pudding', 'Chuck Roast', 'Ciabatta',
               'Cider', 'Cider Vinegar', 'Cilantro', 'Cilantro Leaves', 'Cinnamon', 'Cinnamon Stick', 'Clams',
               'Clear Honey', 'Clotted Cream', 'Cloves', 'Coco Sugar', 'Cocoa', 'Cocoa Powder', 'Coconut Cream',
               'Coconut Flakes', 'Coconut Milk', 'Cod', 'Colby Jack Cheese', 'Cold Water', 'Condensed Milk',
               'Cooked Beetroot', 'Cooked Chestnut', 'Cooking wine', 'Coriander', 'Coriander Leaves', 'Coriander Seeds',
               'Corn Arepa Filled With Mozarella Cheese', 'Corn Flour', 'Corn Tortillas', 'Corned Beef', 'Cornmeal',
               'Cornstarch', 'Courgettes', 'Couscous', 'Cranberry', 'Cream', 'Cream Cheese', 'Cream Of Tartar',
               'Creamed Corn', 'Creme Fraiche', 'Crusty Bread', 'Cubed Feta Cheese', 'Cucumber', 'Cumin', 'Cumin Seeds',
               'Currants', 'Curry Powder', 'Custard', 'Custard Powder', 'Dark Brown Soft Sugar', 'Dark Brown Sugar',
               'Dark Chocolate', 'Dark Chocolate Chips', 'Dark Rum', 'Dark Soft Brown Sugar', 'Dark Soy Sauce',
               'Demerara Sugar', 'Desiccated Coconut', 'Diced Tomatoes', 'Digestive Biscuits', 'Dijon Mustard', 'Dill',
               'Dill Pickles', 'Doner Meat', 'Doubanjiang', 'Double Cream', 'Dried Apricots', 'Dried Cherries',
               'Dried Chillies', 'Dried Fruit', 'Dried Leaves Of Summer Savoury', 'Dried Mint', 'Dried Oregano',
               'Dried Red Chillies', 'Dried Shrimp', 'Dried White Navy Beans', 'Dried cranberries', 'Dried white beans',
               'Dried white corn', 'Dry White Wine', 'Dry sherry', 'Duck', 'Duck Fat', 'Duck Legs', 'Duck Sauce',
               'Dulce de leche', 'Dutch Stroop', 'Egg', 'Egg Noodles', 'Egg Plants', 'Egg Roll Wrappers', 'Egg Rolls',
               'Egg Wash', 'Egg White', 'Egg Yolks', 'Eggs', 'Emmentaler Cheese', 'Enchilada Sauce', 'English Muffins',
               'English Mustard', 'Extra Virgin Olive Oil', 'Fajita Seasoning', 'Falafel', 'Farfalle',
               'Fast action yeast', 'Feather blade beef', 'Fennel', 'Fennel Bulb', 'Fennel Seeds', 'Fenugreek',
               'Fermented Black Beans', 'Feta', 'Fettuccine', 'Fideo', 'Figs', 'Fillet Of Steak', 'Filo Pastry',
               'Fine Yellow Cornmeal', 'Fish Sauce', 'Fish Seasoning', 'Fish Stock', 'Fish fillet', 'Five Spice Powder',
               'Flaked Almonds', 'Flat Rice Noodles', 'Flax Eggs', 'Flour', 'Flour Tortilla', 'Floury Potatoes',
               'Free-range Egg, Beaten', 'Free-range Eggs, Beaten', 'Freekeh', 'French Lentils', 'Fresh Basil',
               'Fresh Thyme', 'Freshly Chopped Parsley', 'Fried Ripe Bananas', 'Fries', 'Fromage Frais',
               'Frozen Mixed Berries', 'Frozen Peas', 'Frozen Seafood mix', 'Fruit Mix', 'Full Fat Yogurt',
               'Full fat sour cream', 'Galangal', 'Galangal Paste', 'Garam Masala', 'Garlic', 'Garlic Bulb',
               'Garlic Clove', 'Garlic Granules', 'Garlic Powder', 'Garlic Sauce', 'Gelatine Leafs', 'German Sausages',
               'Ghee', 'Gherkin Relish', 'Ginger', 'Ginger Cordial', 'Ginger Garlic Paste', 'Ginger Paste',
               'Glace Cherry', 'Goat Meat', 'Goats Cheese', 'Gochujang', 'Golden Caster Sugar', 'Golden Syrup',
               'Goose Fat', 'Gouda Cheese', 'Graham Cracker Crumbs', 'Grand Marnier', 'Granulated Sugar',
               'Grape Nut Cereal', 'Grape Tomatoes', 'Grape leaves', 'Greek Yogurt', 'Green Beans',
               'Green Cardamom Pods', 'Green Chilli', 'Green Olives', 'Green Pepper', 'Green Red Lentils',
               'Green Salsa', 'Ground Allspice', 'Ground Almonds', 'Ground Annatto', 'Ground Beef', 'Ground Cardomom',
               'Ground Cinnamon', 'Ground Clove', 'Ground Coriander', 'Ground Cumin', 'Ground Ginger', 'Ground Nut Oil',
               'Ground Nutmeg', 'Ground Oats', 'Ground Pistachios', 'Ground Poppy seeds', 'Ground Pork', 'Ground Sugar',
               'Gruyère', 'Haddock', 'Hail', 'Hake', 'Ham', 'Hard Taco Shells', 'Haricot Beans', 'Harissa Spice',
               'Hazlenuts', 'Heavy Cream', 'Herring', 'High Heat Cooking Oil', 'Hind Shank',
               'Hispi (sweetheart) Cabbage', 'Hoisin Sauce', 'Honey', 'Horseradish', 'Hot Beef Stock',
               'Hot Chilli Powder', 'Hot Smoked Flaked Salmon', 'Hot smoked paprika', 'Hotsauce', 'Hummus', 'Ice Cream',
               'Iceberg Lettuce', 'Icing Sugar', 'Instant Yeast', 'Italian Fennel Sausages', 'Italian Seasoning',
               'Jalapeno', 'Jam', 'Jamaican Curry Powder', 'Jasmine Rice', 'Jerk', 'Jersey Royal Potatoes',
               'Jerusalem Artichokes', 'Jumbo Shrimp', 'Juniper Berries', 'Kabanos Sausages', 'Kabse Spice', 'Kale',
               'Khus Khus', 'Kidney Beans', 'Kielbasa', 'King Prawns', 'Knafeh', 'Kosher Salt', 'Lamb', 'Lamb Kidney',
               'Lamb Leg', 'Lamb Loin Chops', 'Lamb Mince', 'Lamb Shanks', 'Lamb Shoulder', 'Lamb Stock', 'Lard',
               'Lasagne Sheets', 'Lean Minced Beef', 'Lean Minced Steak', 'Leek', 'Lemon', 'Lemon Juice', 'Lemon Zest',
               'Lemongrass', 'Lemongrass Stalks', 'Lemons', 'Lentils', 'Lettuce', 'Light Brown Soft Sugar', 'Light Rum',
               'Lime', 'Lime Leaves', 'Lime juice', 'Linguine Pasta', 'Liquid Cheese', 'Little Gem Lettuce', 'Macaroni',
               'Mackerel', 'Madras Paste', 'Malai', 'Malt Vinegar', 'Maple Syrup', 'Marinated Tofu', 'Marjoram',
               'Mars Bar', 'Marzipan', 'Mascarpone', 'Massaman Curry Paste', 'Mature Cheddar', 'Mayonnaise',
               'Medjool Dates', 'Melted Butter', 'Meringue Nests', 'Milk', 'Milk Chocolate', 'Minced Beef',
               'Minced Garlic', 'Minced Pork', 'Mincemeat', 'Miniature Marshmallows', 'Mint', 'Mirin',
               'Mixed Beef Cuts', 'Mixed Grain', 'Mixed Peel', 'Mixed Spice', 'Mixed peppers', 'Mixture Powder',
               'Molasses', 'Monkfish', 'Monterey Jack Cheese', 'Morcilla', 'Mozzarella', 'Mozzarella Balls', 'Muffins',
               'Mulukhiyah', 'Mung Bean Sprouts', 'Muscovado Sugar', 'Mushrooms', 'Mussels', 'Mustard',
               'Mustard Powder', 'Mustard Seeds', 'Naan Bread', 'Napa Cabbage', 'Natural Yoghurt', 'New Potatoes',
               'Noodles', 'Nutella', 'Nutmeg', 'Oatmeal', 'Oats', 'Oil', 'Olive Oil', 'Onion', 'Onion Salt', 'Onions',
               'Orange', 'Orange Blossom Water', 'Orange Juice', 'Orange Zest', 'Oregano', 'Oreo Cream Biscuits',
               'Oxtail', 'Oyster Mushrooms', 'Oyster Sauce', 'Oysters', 'Paccheri Pasta', 'Padron peppers',
               'Paella Rice', 'Pak Choi', 'Palm Sugar', 'Panang Curry Paste', 'Paneer', 'Papelon', 'Pappardelle Pasta',
               'Paprika', 'Parma Ham', 'Parmesan', 'Parmesan Cheese', 'Parmigiano-reggiano', 'Parsley', 'Passata',
               'Passion Fruit Pulp', 'Peach Juice', 'Peaches', 'Peanut Brittle', 'Peanut Butter', 'Peanut Cookies',
               'Peanut Oil', 'Peanuts', 'Pears', 'Peas', 'Pecan Nuts', 'Pecorino', 'Penne Pasta', 'Penne Rigate',
               'Pepper', 'Peppercorns', 'Persian Cucumber', 'Petit Pois', 'Phyllo Dough', 'Pickle Juice',
               'Pico De Gallo Sauce', 'Pilchards', 'Pine Nuts', 'Pineapple Chunks', 'Pineapple Juice',
               'Pink Food Colouring', 'Pinto Beans', 'Pistachio', 'Pistachio Paste', 'Pita Bread',
               'Pitted Black Olives', 'Pitted Dates', 'Plain Chocolate', 'Plain Flour', 'Plum Jam', 'Plum Sauce',
               'Plum Tomatoes', 'Polish Kabanos', 'Polish Sausage', 'Pomegranate', 'Pomegranate Molasses',
               'Poppy Seeds', 'Pork', 'Pork Back Ribs', 'Pork Chops', 'Pork Shoulder', 'Pork Shoulder Steaks',
               'Pork Tenderloin', 'Pork belly slices', 'Pork knuckle', 'Porridge oats', 'Potato Starch', 'Potatoe Buns',
               'Potatoes', 'Powdered Sugar', 'Prawns', 'Pre-fried Tequeños', 'Pretzels', 'Prosciutto', 'Prunes',
               'Puff Pastry', 'Pul Biber', 'Pumpkin', 'Purple Sprouting Broccoli', 'Quinoa', 'Radish', 'Rainbow Trout',
               'Raisins', 'Rapeseed Oil', 'Ras el hanout', 'Raspberries', 'Raspberry Jam', 'Raw Frozen Prawns',
               'Raw King Prawns', 'Raw Vegetables', 'Raw tiger prawns', 'Ready rolled shortcrust pastry', 'Red Cabbage',
               'Red Chilli', 'Red Chilli Flakes', 'Red Chilli Powder', 'Red Food Colouring', 'Red Onions', 'Red Pepper',
               'Red Pepper Flakes', 'Red Pepper Paste', 'Red Potatoes', 'Red Snapper', 'Red Wine', 'Red Wine Jelly',
               'Red Wine Vinegar', 'Redcurrants', 'Refried Beans', 'Rhubarb', 'Rice', 'Rice Flour Pancakes',
               'Rice Krispies', 'Rice Noodles', 'Rice Paper Sheets', 'Rice Stick Noodles', 'Rice Vermicelli',
               'Rice Vinegar', 'Rice wine', 'Ricotta', 'Rigatoni', 'Roasted Peanut', 'Roasted Vegetables',
               'Roasted pepper', 'Rocket', 'Rolled Oats', 'Romano Pepper', 'Rose water', 'Rosemary', 'Rum',
               'Runner Beans', 'Russet Potato', 'Rye', 'Rye Bread', 'Saffron', 'Sage', 'Sake', 'Salmon', 'Salsa',
               'Salt', 'Salt Cod', 'Salted Butter', 'Sardines', 'Saskatoon Berries', 'Sauerkraut', 'Sausages',
               'Savoy Cabbage', 'Sazon', 'Scallions', 'Scotch Bonnet', 'Sea Bass', 'Sea Bass Fillets', 'Sea Salt',
               'Seafood stock', 'Seasoned Rice Vinegar', 'Seasoning', 'Self-raising Flour', 'Semi-skimmed Milk',
               'Semolina', 'Semolina Flour', 'Serrano Ham', 'Sesame Seed', 'Sesame Seed Burger Buns', 'Sesame Seed Oil',
               'Sevaiiya', 'Shallots', 'Shaoxing Wine', 'Shelled Hazelnuts', 'Sherry', 'Sherry vinegar',
               'Shiitake Mushrooms', 'Shortcrust Pastry', 'Shortening', 'Shredded Coconut', 'Shredded Meat',
               'Shredded Mexican Cheese', 'Shredded Monterey Jack Cheese', 'Shrimp', 'Shrimp Paste', 'Shrimp Stock',
               'Sichuan Pepper', 'Silken Tofu', 'Single Cream', 'Sirloin Steak tips', 'Sirloin steak', 'Skirty Steak',
               'Small Potatoes', 'Smoked Haddock', 'Smoked Paprika', 'Smoked Salmon', 'Smoked Turkey Neck',
               'Smoky Aïoli', 'Smoky Paprika', 'Snapper Fish', 'Snow Peas', 'Soda Water', 'Sour Cream',
               'Soured cream and chive dip', 'Soy Sauce', 'Soya Bean', 'Soya Milk', 'Spaghetti', 'Speculaas Spice Mix',
               'Spinach', 'Split Peas', 'Spring Onions', 'Squash', 'Squid', 'Sriracha', 'Stale bread', 'Star Anise',
               'Starch', 'Stilton Cheese', 'Stir-fry Vegetables', 'Stoned Dates', 'Stout', 'Strawberries',
               'Streaky Bacon', 'Strong White Flour', 'Strong Wholemeal Flour', 'Strong white bread flour', 'Suet',
               'Sugar', 'Sugar Snap Peas', 'Sugar Syrup', 'Sultanas', 'Sumac', 'Sun-Dried Tomatoes', 'Sunflower Oil',
               'Sushi Rice', 'Swede', 'Sweet Peppadew Peppers', 'Sweet Potatoes', 'Sweet Red Peppers', 'Sweet Sherry',
               'Sweetcorn', 'Sweetened Condensed Milk', 'Szechuan Peppercorns', 'Tabasco Sauce', 'Tagliatelle',
               'Tahini', 'Tahini Paste', 'Tamarind Ball', 'Tamarind Paste', 'Tamarind Pulp', 'Tarragon Leaves',
               'Tempeh', 'Thai Chilli Jam', 'Thai Fish Sauce', 'Thai Green Curry Paste', 'Thai Red Curry Paste',
               'Thyme', 'Tiger Prawns', 'Tinned Tomatos', 'Toast', 'Toffee Popcorn', 'Tofu', 'Tomato', 'Tomato Ketchup',
               'Tomato Puree', 'Tomato Sauce', 'Tomatoes', 'Toor Dal', 'Tortillas', 'Treacle', 'Tripe', 'Trout',
               'Truffle Oil', 'Tuna', 'Turkey', 'Turkey Ham', 'Turkey Mince', 'Turkey Neck', 'Turkish Delight',
               'Turmeric', 'Turmeric Powder', 'Turnips', 'Udon Noodles', 'Unflavoured Gelatin', 'Unsalted Beef Stock',
               'Unsalted Butter', 'Unsalted Pistachio', 'Unsweetened Cocoa', 'Unsweetened Coconut Milk',
               'Unwaxed Lemon', 'Unwaxed Lime', 'Vanilla', 'Vanilla Bean Paste', 'Vanilla Custard', 'Vanilla Extract',
               'Veal', 'Vegan Butter', 'Vegan White Wine Vinegar', 'Vegetable Oil', 'Vegetable Shortening',
               'Vegetable Stock', 'Vegetable Stock Cube', 'Vermicelli Pasta', 'Vermicelli Rice Noodles',
               'Vinaigrette Dressing', 'Vine Leaves', 'Vine Tomatoes', 'Vinegar', 'Walnuts', 'Warm Water', 'Water',
               'Water Chestnut', 'Whipping Cream', 'White Asparagus', 'White Bread Mix', 'White Cabbage',
               'White Chocolate', 'White Chocolate Chips', 'White Cornmeal', 'White Fish', 'White Fish Fillets',
               'White Flour', 'White Masarepa', 'White Sauerkraut', 'White Vinegar', 'White Wine', 'White Wine Vinegar',
               'White Yam', 'White bread', 'Whole Milk', 'Whole Wheat', 'Whole black peppercorns', 'Wholegrain Bread',
               'Wholegrain Mustard', 'Wild Garlic Leaves', 'Wild Mushrooms', 'Wonton Skin', 'Wood Ear Mushrooms',
               'Worcestershire Sauce', 'Yautia', 'Yeast', 'Yellow Food Colouring', 'Yellow Masarepa', 'Yellow Onion',
               'Yellow Pepper', 'Yellow Split Peas', 'Yogurt', 'Yukon Gold Potatoes', 'Zucchini', 'barramundi',
               'jamón ibérico', 'makrut lime leaves', 'manchego', 'sweet chilli sauce', 'sweet smoked paprika',
               'vanilla pod', 'vanilla sugar', 'västerbottensost cheese']

RECIPES = {'15-minute chicken & halloumi burgers': '53085', 'Adana kebab': '53262', 'Air Fryer Egg Rolls': '53373',
           'Air fryer patatas bravas': '53158', 'Ajo blanco': '53169', 'Alfajores': '53138',
           'Algerian Bouzgene Berber Bread with Roasted Pepper Sauce': '53284', 'Algerian Carrots': '53282',
           'Algerian Flafla (Bell Pepper Salad)': '53288', 'Algerian Kefta (Meatballs)': '53281',
           'Anzac biscuits': '53111', 'Apam balik': '53049', 'Apple & Blackberry Crumble': '52893',
           'Apple Frangipan Tart': '52768', 'Apple cake': '53380', 'Apricot & Turkish delight mess': '53276',
           'Arepa Pabellón': '53334', 'Arepa pelua': '53329', 'Arroz al horno (baked rice)': '53156',
           'Arroz con gambas y calamar': '53147', 'Asado': '53133', 'Aubergine & hummus grills': '53278',
           'Aubergine couscous salad': '53267', 'Aussie Burgers': '53099', 'Authentic Norwegian Kransekake': '53127',
           'Avocado dip with new potatoes': '53107', 'Ayam Percik': '53050', 'Æbleskiver': '53120',
           'BBQ Pork Sloppy Joes': '52995', 'Baba Ghanoush': '53094', 'Baingan Bharta': '52807',
           'Baked salmon with fennel & tomatoes': '52959',
           'Bakewell tart': '52767', 'Baklava with spiced nuts, ricotta & chocolate': '53279',
           'Banana Pancakes': '52855', 'Bang bang prawn salad': '53239', 'Barbecue pork buns': '53242',
           'Barramundi with Moroccan spices': '53103', 'Battenberg Cake': '52894', 'Bean & Sausage Hotpot': '52848',
           'BeaverTails': '52928', 'Beef Asado': '53071',
           'Beef Banh Mi Bowls with Sriracha Mayo, Carrot & Pickled Cucumber': '52997', 'Beef Bourguignon': '52904',
           'Beef Brisket Pot Roast': '52812', 'Beef Caldereta': '53070', 'Beef Dumpling Stew': '52873',
           'Beef Empanadas': '53317', 'Beef Lo Mein': '52952', 'Beef Mandi': '53359', 'Beef Mechado': '53068',
           'Beef Rendang': '53053', 'Beef Sunday Roast': '52824', 'Beef Wellington': '52803',
           'Beef and Broccoli Stir-Fry': '53366', 'Beef and Mustard Pie': '52874', 'Beef and Oyster pie': '52878',
           'Beef pho': '53238', 'Beef stroganoff': '52834', 'Beetroot & red cabbage sauerkraut': '53307',
           'Beetroot Soup (Borscht)': '53078', 'Beetroot latkes': '53313', 'Beetroot pancakes': '53316',
           'Big Mac': '53013', 'Bigos (Hunters Stew)': '53018', "Bigos (Polish hunter's stew)": '53300',
           'Bistek': '53069', 'Bitterballen (Dutch meatballs)': '52979', 'Blackberry Fool': '52891',
           'Blini Pancakes': '53080', 'Blueberry & lemon friands': '53100', 'Borsch': '53311',
           'Boulangère Potatoes': '52914', 'Boxty Breakfast': '53036', 'Braised Beef Chilli': '52826',
           'Braised stuffed cabbage': '53305', 'Bread and Butter Pudding': '52792', 'Bread omelette': '53076',
           'Breakfast Potatoes': '52965', 'Brie wrapped in prosciutto & brioche': '52913',
           'Broccoli & Stilton soup': '52842', 'Brown Stew Chicken': '52940',
           'Brun Lapskaus (Norwegian Beef Vegetable Stew)': '53126', 'Bryndzové Halušky': '53190',
           'Bubble & Squeak': '52885', 'Budino Di Ricotta': '52961', 'Burek': '53060', 'Cabbage Soup (Shchi)': '53077',
           'Cacik': '53256', 'Cajun spiced fish tacos': '52819', 'Callaloo Jamaican Style': '52939',
           'Callaloo and SaltFish': '53361', 'Canadian Butter Tarts': '52923', 'Carbonada Criolla': '53141',
           'Caribbean Tamarind balls': '53360', 'Carrot Cake': '52897', 'Cashew Ghoriba Biscuits': '52976',
           'Cassava pizza': '53330', 'Cevapi Sausages': '53055', 'Chakchouka ': '52969', 'Challah': '53310',
           'Cheese Borek': '53290', 'Chelsea Buns': '52898', 'Chick-Fil-A Sandwich': '53016',
           'Chicken & chorizo rice pot': '53161', 'Chicken & mushroom Hotpot': '52846',
           'Chicken Alfredo Primavera': '52796', 'Chicken Basquaise': '52934', 'Chicken Congee': '52956',
           'Chicken Couscous': '52850', 'Chicken Enchilada Casserole': '52765',
           'Chicken Fajita Mac and Cheese': '52818', 'Chicken Fried Rice': '53367', 'Chicken Ham and Leek Pie': '52875',
           'Chicken Handi': '52795', 'Chicken Karaage': '52831', 'Chicken Mandi': '53358', 'Chicken Marengo': '52920',
           'Chicken Parmentier': '52879', 'Chicken Quinoa Greek Salad': '53011',
           'Chicken Shawarma with homemade garlic herb yoghurt sauce': '53218',
           'Chicken wings with cumin, lemon & garlic': '53261', 'Chicken with saffron, raisins & pine nuts': '53186',
           'Chickpea Fajitas': '52870', 'Chickpea, chorizo & spinach stew': '53166',
           'Chilli ginger lamb chops': '53265', 'Chilli prawn linguine': '52839', 'Chinese Orange Chicken': '53365',
           'Chinese Tomato Egg Stir Fry': '53372', 'Chinon Apple Tarts': '52910', 'Chivito sandwich': '53319',
           'Chivito uruguayo': '53063', 'Choc Chip Pecan Pie': '52856', 'Chocolate Avocado Mousse': '52853',
           'Chocolate Caramel Crispy': '52966', 'Chocolate Coconut Squares': '53101', 'Chocolate Gateau': '52776',
           'Chocolate Raspberry Brownies': '52860', 'Chocolate Souffle': '52905', 'Chocolate alfajores': '53320',
           'Chocolate churros with chocolate & salted caramel sauce': '53170', 'Chocolate empanadas': '53324',
           'Chorba Hamra bel Frik (Algerian Lamb, Tomato, and Freekeh Soup)': '53289', 'Choripán': '53136',
           'Chorizo & chickpea soup': '53168', 'Chorizo & soft-boiled egg salad': '53157',
           'Chorizo & tomato salad': '53185', 'Chorizo, potato & cheese omelette': '53159',
           'Christmas Pudding Flapjack': '52788', 'Christmas Pudding Trifle': '52989', 'Christmas cake': '52990',
           'Chtitha Batata (Algerian Potato Stew)': '53283', 'Churros': '53153', 'Cinnamon buns': '53116',
           'Clam chowder': '52840', 'Clam, chorizo & white bean stew': '53154', 'Classic Christmas pudding': '52988',
           'Classic Tourtière': '53343', 'Coddled pork with cider': '53037', 'Coq au vin': '52832', 'Corba': '52977',
           'Corned Beef Hash': '53096', 'Corned Beef and Cabbage': '52998',
           'Corned Beef and Cabbage – Jamaican Style': '53350', 'Cornes de Gazelle (Gazelle Horns)': '53291',
           'Cream Cheese Tart': '52779', 'Creamy Tomato Soup': '52841', 'Crema Catalana': '53148',
           'Crispy Eggplant': '53072', 'Crispy Sausages and Greens': '52999', 'Croatian Bean Stew': '53058',
           'Croatian lamb peka': '53056', 'Crock Pot Chicken Baked Tacos': '52830', 'Cucumber & fennel salad': '53309',
           'Cumberland Pie': '53098', 'Dal fry': '52785', 'Date squares': '53338',
           'Drunken noodles (pad kee mao)': '53193', 'Duck Confit': '52907', 'Dulce de Leche': '53137',
           'Dundee cake': '52899', 'Dutch poffertjes (mini pancakes)': '53379', 'Dutch stroopwafel': '53382',
           'Dziriat (Algerian Almond Tarts)': '53285', 'Easy Spanish chicken': '53143', 'Eccles Cakes': '52888',
           'Egg Drop Soup': '52955', 'Egg Foo Young': '53370', 'Eggplant Adobo': '53073', 'Egyptian Fatteh': '53031',
           'Empanadas': '53134', 'English Breakfast': '52895', 'Ensaimada': '53149', 'Escovitch Fish': '52944',
           'Eton Mess': '52791', 'Ezme': '53254', 'Fainá': '53139', 'Falafel': '53266',
           'Falafel Pita Sandwich with Tahini Sauce': '53091',
           'Fasoliyyeh Bi Z-Zayt (Syrian Green Beans with Olive Oil)': '53092', 'Fašírky': '53188',
           'Fennel Dauphinoise': '52919', 'Feteer Meshaltet': '53030', 'Fettuccine Alfredo': '53064',
           'Fettucine alfredo': '52835', 'Figgy Duff': '53342', 'Fish Soup (Ukha)': '53079',
           'Fish Stew with Rouille': '52918', 'Fish fofos': '53043', 'Fish pie': '52802',
           'Fiskesuppe (Creamy Norwegian Fish Soup)': '53122', 'Flamiche': '52906', 'Flan': '53322',
           'Flapper Pie': '53341', 'French Lentils With Garlic and Thyme': '52815', 'French Omelette': '52915',
           'French Onion Chicken with Roasted Carrots & Mashed Potatoes': '52996', 'French Onion Soup': '52903',
           'Fresh sardines': '53061', 'Fried calamari': '53178', 'Fruit and Cream Cheese Breakfast Pastries': '52957',
           'Ful Medames': '53025', 'Full English Breakfast': '52896', 'Fyrstekake – Norwegian Prince Cake': '53131',
           'Fårikål (Norwegian National Dish)': '53123', 'Gambas al ajillo': '53144', 'Garides Saganaki': '52764',
           'Garlicky prawns with sherry': '53180', 'General Tsos Chicken': '52951', 'Gevulde speculaas': '53381',
           'Gigantes Plaki': '53012', 'Golabki (cabbage roll)': '53021', 'Grape Nut Ice Cream': '53346',
           'Griddled aubergines with sesame dressing': '53274', 'Griddled flatbreads': '53272',
           'Grilled Mac and Cheese Sandwich': '52829', 'Grilled Portuguese sardines': '53041',
           'Grilled aubergines with spicy chickpeas & walnut sauce': '53255',
           'Grilled eggplant with coconut milk': '53074', 'Ham croquetas': '53179', 'Ham hock colcannon': '53035',
           'Hodge Podge': '53340', 'Home-made Mandazi': '52967',
           'Honey Balsamic Chicken with Crispy Broccoli & Potatoes': '52993', 'Honey Teriyaki Salmon': '52773',
           'Honey Yogurt Cheesecake': '53007', 'Hot Chocolate Fudge': '52787', 'Hot and Sour Soup': '52954',
           'Hot cumin lamb wrap with crunchy slaw & spicy mayo': '53258', 'Hummus': '53269',
           'Imam bayildi with BBQ lamb & tzatziki': '53253', 'Irish stew': '52781', 'Jam Roly-Poly': '52890',
           'Jam jam cookies': '53339', 'Jamaican Banana Fritters': '53351', 'Jamaican Beef Patties': '52938',
           'Jamaican Boiled Dumplings': '53353', 'Jamaican Cornmeal Porridge': '53363',
           'Jamaican Curry Chicken Recipe': '53345', 'Jamaican Curry Goat': '53354',
           'Jamaican Curry Shrimp Recipe': '53362', 'Jamaican Festival (Sweet Dumpling)': '53355',
           'Jamaican Fried Dumplings': '53356', 'Jamaican Instant Pot Rice and Beans': '53352',
           'Jamaican Pepper Shrimp': '53349', 'Jamaican Rice and Peas': '53357', 'Jamaican Spice Bun Recipe': '53348',
           'Jamaican Steamed Cabbage': '53364', 'Jamaican Sweet Potato Pudding': '53344',
           'Jamon & wild garlic croquetas': '53145', 'Japanese Katsudon': '53034', 'Japanese gohan rice': '53033',
           'Jerk chicken with rice & peas': '52937', 'Jiggs Dinner': '53335', 'Kabse': '53220', 'Kafteji': '52971',
           'Kapsalon': '52769',
           'Karbonader (Lean Beef Patties) with Caramelized Onions': '53125', 'Katsu Chicken curry': '52820',
           'Kedgeree': '52887', 'Keleya Zaara': '52974', 'Kentucky Fried Chicken': '52813',
           'Kenyan Beef Curry': '53112', 'Key Lime Pie': '52859', 'Khobz el Dar (Algerian Semolina Bread)': '53286',
           'Kidney Bean Curry': '52868', 'Knafeh': '53216', 'Kofta burgers': '53257', 'Koshari': '53027',
           'Krispy Kreme Donut': '53015',
           'Kumpir': '52978', 'Kung Pao Chicken': '52945', 'Kung Po Prawns': '52946',
           'Kvæfjord Cake “Verdens Beste” (World’s Best Cake)': '53128', 'Laksa King Prawn Noodles': '52821',
           'Lamb & apricot meatballs': '53277', 'Lamb Biryani': '52805', 'Lamb Pilaf (Plov)': '53083',
           'Lamb Rogan josh': '52808', 'Lamb Tagine': '52843', 'Lamb Tzatziki Burgers': '53010',
           'Lamb and Lemon Souvlaki': '53009', 'Lamb and Potato pie': '52877', 'Lamb tomato and sweet spices': '52782',
           'Lamingtons': '53104', 'Lancashire hotpot': '52884', 'Lasagna Sandwiches': '52987', 'Lasagne': '52844',
           'Leblebi Soup': '52973', 'Lemongrass beef stew with noodles': '53211', 'Locro': '53146',
           'Ma Po Tofu': '52947', 'Madeira Cake': '52900', 'Mamoul (Eid biscuits)': '53221',
           'Massaman Beef curry': '52827', 'Matambre a la Pizza': '53140', 'Matar Paneer': '52865',
           'Mazariner – Scandinavian Almond Tartlets': '53132', 'Mbuzi Choma (Roasted Goat)': '52968',
           'McSinghs Scotch pie': '52880', 'Mediterranean Pasta Salad': '52777', 'Mee goreng mamak': '53048',
           'Migas': '53086', 'Milanesa': '53135', 'Mince Pies': '52991', 'Minced Beef Pie': '52876',
           'Mini bundt cakes': '53304', 'Mini chilli beef pies': '53109', 'Molasses Baked Beans': '53336',
           'Montreal Smoked Meat': '52927', 'Moroccan Carrot Soup': '53047', 'Moussaka': '53006', 'Mulukhiyah': '53029',
           'Mushroom & Chestnut Rotolo': '52864', 'Mushroom soup with buckwheat': '53059', 'Mustard champ': '53038',
           'Mutabbaq': '53223', 'Nanaimo Bars': '52924', 'Napa Cabbage with Dried Shrimp': '53377',
           'Nasi lemak': '53051', 'New York cheesecake': '52858', 'No-Churn Rum Raisin Ice Cream': '53347',
           'Noodle bowl salad': '53245', 'Nordic smørrebrød with asparagus and horseradish cream': '53117',
           'Norwegian Krumkake': '53129', 'Norwegian Potato Lefse': '53121', 'Nutty Chicken Curry': '52851',
           'Oatmeal pancakes': '53331', 'Osso Buco alla Milanese': '52810', 'Oxtail with broad beans': '52943',
           'Pad See Ew': '52774', 'Pad Thai': '53191', 'Padron peppers': '53150', 'Paella': '53151',
           'Pan-fried hake, white bean & chorizo broth': '53152', 'Panang chicken curry (kaeng panang gai)': '53192',
           'Pancakes': '52854', 'Parkin Cake': '52902', 'Passion fruit mousse': '53333',
           'Paszteciki (Polish Pasties)': '53017', 'Patatas bravas': '53172', 'Pate Chinois': '52930',
           'Peach & Blueberry Grunt': '52862', 'Peanut Butter Cheesecake': '52861', 'Peanut Butter Cookies': '52958',
           'Pear Tarte Tatin': '52916', 'Piernik (Polish gingerbread)': '53292', 'Pierogi (Polish Dumplings)': '53019',
           'Pilchard puttanesca': '52837', 'Piri-piri chicken and slaw': '53039',
           'Pistachio Kunafa Chocolate Cake and Cupcakes': '53224', 'Pistachio cake': '53293',
           'Pisto con huevos': '53160', 'Pizza Express Margherita': '53014', 'Polish chocolate & walnut cake': '53295',
           'Polish doughnuts (Pączki)': '53298', 'Polish patties (kotlety)': '53299', 'Pollo en pepitoria': '53162',
           'Polskie Nalesniki (Polish Pancakes)': '53022', 'Pomegranate salad': '53297',
           'Pork & sauerkraut goulash': '53301', 'Pork Cassoulet': '52847', 'Pork rib bortsch': '53306',
           'Portuguese barbecued pork (Febras assadas)': '53044', 'Portuguese custard tarts': '53046',
           'Portuguese fish stew (Caldeirada de peixe)': '53045', 'Portuguese prego with green piri-piri': '53042',
           'Postre Chajá': '53323', 'Potato Gratin with Chicken': '52780', 'Potato Salad (Olivier Salad)': '53081',
           'Pouding chomeur': '52932', "Poulet Roti a l'Algerienne (Algerian Roast Chicken)": '53280',
           'Poutine': '52804', 'Prawn & Fennel Bisque': '52922', 'Prawn & noodle salad with crispy shallots': '53244',
           'Prawn stir-fry': '53200', 'Prawns with Romesco sauce': '53174', 'Provençal Omelette Cake': '52921',
           'Pumpkin Pie': '52857', 'Purple sprouting broccoli tempura with nuoc cham': '53230',
           'Quick gazpacho': '53173', 'Quick salt & pepper squid': '53108', 'Ramen Noodles with Boiled Egg': '53383',
           'Rappie Pie': '52933', 'Raspberry mousse': '53303', 'Raspeballer (Norwegian Potato Dumplings)': '53124',
           'Ratatouille': '52908', 'Recheado Masala Fish': '52809', 'Red Peas Soup': '52941',
           'Red curry chicken kebabs': '53204', 'Red onion pickle': '53115', 'Ribollita': '52811',
           'Rice paper dumplings': '53227', 'Rigatoni with fennel sausage sauce': '52783',
           "Roast aubergine with goat's cheese & toasted flatbread": '53273',
           'Roast fennel and aubergine paella': '52942',
           'Roasted Eggplant With Tahini, Pine Nuts, and Lentils': '52816',
           'Roasted chicken with creamy walnut sauce': '53268', 'Rock Cakes': '52901', 'Rocky Road Fudge': '52786',
           'Rogaliki (Polish Croissant Cookies)': '53024', 'Rosemary braised red cabbage with kabanos': '53315',
           'Rosol (Polish Chicken Soup)': '53020', 'Roti john': '53052', 'Rye bread': '53308',
           'Rømmegrøt – Norwegian Sour Cream Porridge': '53118', 'Salmon Avocado Salad': '52960',
           'Salmon Eggs Eggs Benedict': '52962', 'Salmon Prawn Risotto': '52823', 'Salmon noodle soup': '53234',
           'Salmon noodle wraps': '53248', 'Salt & pepper squid': '53233', 'Salt cod tortilla': '53171',
           'Salted Caramel Cheescake': '52833', 'Saltfish and Ackee': '52936', 'Saskatoon Pie': '53337',
           'Sauerkraut pierogi': '53296', 'Sauerkraut pierogii': '53314',
           'Sea bass with sizzled ginger, chilli & spring onions': '53247', 'Seafood fideuà': '52836',
           'Seafood rice': '53167', 'Seri muka kuih': '53054', 'Sesame Cucumber Salad': '53378', 'Shakshouka': '53215',
           'Shakshuka': '52963', 'Shakshuka Feta Cheese': '53219', 'Shawarma': '53028', 'Shawarma bread': '53226',
           'Shawarma chuck roast wrap': '53217', 'Shrimp Chow Fun': '52953', 'Shrimp With Snow Peas': '53375',
           'Sichuan Eggplant': '53374', 'Sichuan Style Stir-Fried Chinese Long Beans': '53371',
           'Silken Tofu with Sesame Soy Sauce': '53369', 'Singapore Noodles with Shrimp': '53368',
           'Skillet Apple Pork Chops with Roasted Sweet Potatoes & Zucchini': '52994',
           'Sledz w Oleju (Polish Herrings)': '53023', 'Slow-roast lamb with cinnamon, fennel & citrus': '53260',
           'Slow-roasted ham with lemon, garlic & sage': '53302', 'Smoked Haddock Kedgeree': '52964',
           'Smoked aubergine purée': '53259', 'Smoky Lentil Chili with Squash': '52784',
           'Smoky chicken skewers': '53264', 'Snert (Dutch Split Pea Soup)': '52981',
           'Soy-Glazed Meatloaves with Wasabi Mashed Potatoes & Roasted Carrots': '52992',
           'Spaghetti Bolognese': '52770', 'Spaghetti alla Carbonara': '52982',
           'Spaghetti with Spanish flavours': '53177', 'Spanish Chicken': '53164', 'Spanish Tortilla': '52872',
           'Spanish beans with chicken & chorizo': '53181', 'Spanish chicken pie': '53155',
           'Spanish fig & almond balls': '53163', 'Spanish meatballs with clams, chorizo & squid': '53183',
           'Spanish rice & prawn one-pot': '53184', 'Spanish seafood rice': '53182',
           'Spanish tomato bread with jamón Serrano': '53176',
           'Spanish-style slow-cooked lamb shoulder & beans': '53175', 'Spiced smoky barbecued chicken': '53105',
           'Spiced tortilla': '53142', 'Spicy Arrabiata Penne': '52771', 'Spicy North African Potato Salad': '52797',
           'Spicy Thai prawn noodles': '53209', 'Spinach & Ricotta Cannelloni': '52849', 'Split Pea Soup': '52925',
           'Spotted Dick': '52886', 'Spring onion and prawn empanadas': '53040', 'Squash linguine': '52866',
           'Squid, chickpea & chorizo salad': '53102', 'Stamppot': '52980', 'Steak & Vietnamese noodle salad': '53229',
           'Steak Diane': '52935', 'Steak and Kidney Pie': '52881', 'Sticky Chicken': '53110',
           'Sticky Toffee Pudding': '52883', 'Sticky Toffee Pudding Ultimate': '52793',
           'Stir-fried chicken with chillies & basil': '53201',
           'Stovetop Eggplant With Harissa, Chickpeas, and Cumin Yogurt': '52817', 'Strawberries Romanoff': '53082',
           'Strawberry Rhubarb Pie': '53005', 'Stuffed Bell Peppers with Quinoa and Black Beans': '53067',
           'Stuffed Lamb Tomatoes': '53008', 'Sugar Pie': '52931',
           'Suksessterte (Norwegian almond “success cake”)': '53130', 'Sukuma Wiki': '53113',
           'Šúĺlance s Makom': '53187', 'Summer Pistou': '52911',
           'Summer Pudding': '52889', 'Sushi': '53065', 'Sweet and Sour Chicken': '53376',
           'Sweet and Sour Pork': '52949', 'Sweet potato salad': '53275', 'Syrian Bread': '53089',
           'Syrian Rice with Meat': '53095', 'Syrian Spaghetti': '53093', 'Szechuan Beef': '52950',
           'Tahini Lentils': '52869',
           'Tajine de Poulet aux Carottes et Patates Douces (Chicken and Sweet Potato Tagine)': '53287',
           'Tall Skoleboller': '53119', 'Tamiya': '53026', 'Tandoori chicken': '52806', 'Tangy cabbage slaw': '53312',
           'Tangy carrot, cabbage & onion salad': '53246', 'Tarte Tatin': '52909',
           'Teriyaki Chicken Casserole': '52772', 'Thai Green Curry': '52814', 'Thai beef stir-fry': '53199',
           'Thai chicken cakes with sweet chilli sauce': '53206', 'Thai coconut & veg broth': '53208',
           'Thai curry noodle soup': '53195', 'Thai drumsticks': '53212', 'Thai fried rice with prawns & peas': '53198',
           'Thai green chicken soup': '53214', 'Thai pork & peanut curry': '53197', 'Thai prawn curry': '53205',
           'Thai pumpkin soup': '53210', 'Thai rice noodle salad': '53203',
           'Thai-style fish broth with greens': '53213', 'Thai-style steamed fish': '53202', 'Three Fish Pie': '52882',
           'Three-cheese souffles': '52912', 'Timbits': '52929', 'Toad In The Hole': '52822',
           'Tofu, greens & cashew stir-fry': '53240', 'Tom kha gai': '53207',
           'Tom yum (hot & sour) soup with prawns': '53196', 'Tom yum soup with prawns': '53194',
           'Tonkatsu pork': '53032', 'Torrijas with sherry': '53165', 'Torta de fiambre': '53318',
           'Tortang Talong': '53075', 'Tourtiere': '52926', 'Traditional Croatian Goulash': '53057',
           'Treacle Tart': '52892', 'Tuna Nicoise': '52852', 'Tuna and Egg Briks': '52975',
           'Tunisian Lamb Soup': '52972', 'Tunisian Orange Cake': '52970', 'Turkey Bánh mì': '53249',
           'Turkey Meatloaf': '52845', 'Turkish lahmacun': '53251', 'Turkish lamb pilau': '53263',
           'Turkish rice (vermicelli rice)': '53252', 'Turkish-style lamb': '53270', 'Ugali – Kenyan cornmeal': '53114',
           'Vanilla alfajores': '53321', 'Vegan Chocolate Cake': '52794', 'Vegan Lasagna': '52775',
           'Vegan banh mi': '53250', 'Vegetable Shepherds Pie': '53000', 'Vegetarian Casserole': '52863',
           'Vegetarian Chilli': '52867', 'Vegetarian Shakshuka': '53222', 'Venetian Duck Ragu': '52838',
           'Venezuelan Arepas': '53325', 'Venezuelan Coconut Chicken': '53327', 'Venezuelan Sancocho': '53326',
           'Venezuelan Shredded Beef': '53328', 'Venezuelan turnovers': '53332',
           'Vietnamese Grilled Pork (bun-thit-nuong)': '52828', 'Vietnamese caramel trout': '53228',
           'Vietnamese chicken salad': '53232', 'Vietnamese lamb shanks with sweet potatoes': '53231',
           'Vietnamese pork salad': '53237', 'Vietnamese prawn spiralized rolls': '53243',
           'Vietnamese veg parcels': '53241', 'Vietnamese-style caramel pork': '53235',
           'Vietnamese-style veggie hotpot': '53236', 'Walnut Roll Gužvara': '53062',
           'Walnut, date & honey cake': '53271', 'Warm roast asparagus salad': '53106',
           'White chocolate creme brulee': '52917', 'Wontons': '52948', 'Yaki Udon': '52871',
           'Yemeni Lahsa (Elite Shakshuka)': '53225', 'Yorkshire Puddings': '53097', 'Zapiekanki': '53294',
           'Zemiakové Placky': '53189',
           }
